In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#documents
doc1 = "I want to start learning to charge something in life"
doc2 = "reading something about life no one else knows"
doc3 = "Never stop learning"
#query string
query = "life learning"

Term Frequency

In [ ]:
doc_lst = doc1.split(" ")
doc_lst

['I',
 'want',
 'to',
 'start',
 'learning',
 'to',
 'charge',
 'something',
 'in',
 'life']

In [ ]:
wordDict_1= dict.fromkeys(set(doc_lst), 0)
wordDict_1

{'I': 0,
 'charge': 0,
 'in': 0,
 'learning': 0,
 'life': 0,
 'something': 0,
 'start': 0,
 'to': 0,
 'want': 0}

In [ ]:
for token in doc_lst:
    wordDict_1[token] +=  1
df = pd.DataFrame([wordDict_1])
df

something  I  in  life  learning  to  start  want  charge
0          1  1   1     1         1   2      1     1       1

In [ ]:
idx = 0
new_col = ["Term Frequency"]    
df.insert(loc=idx, column='Document', value=new_col)
print(df)

         Document  something  I  in  life  learning  to  start  want  charge
0  Term Frequency          1  1   1     1         1   2      1     1       1


In [ ]:
#term -frequenvy :word occurences in a document
def compute_tf(docs_list):
    for doc in docs_list:
        doc1_lst = doc.split(" ")
        wordDict_1= dict.fromkeys(set(doc1_lst), 0)

        for token in doc1_lst:
            wordDict_1[token] +=  1
        df = pd.DataFrame([wordDict_1])
        idx = 0
        new_col = ["Term Frequency"]    
        df.insert(loc=idx, column='Document', value=new_col)
        print(df)
        
compute_tf([doc1, doc2, doc3])

         Document  something  I  in  life  learning  to  start  want  charge
0  Term Frequency          1  1   1     1         1   2      1     1       1
         Document  something  life  else  one  knows  no  about  reading
0  Term Frequency          1     1     1    1      1   1      1        1
         Document  stop  learning  Never
0  Term Frequency     1         1      1


In [ ]:
#Normalized Term Frequency
def termFrequency(term, document):
    normalizeDocument = document.lower().split()
    return normalizeDocument.count(term.lower()) / float(len(normalizeDocument))

In [ ]:
def compute_normalizedtf(documents):
    tf_doc = []
    for txt in documents:
        sentence = txt.split()
        norm_tf= dict.fromkeys(set(sentence), 0)
        for word in sentence:
            norm_tf[word] = termFrequency(word, txt)
        tf_doc.append(norm_tf)
        df = pd.DataFrame([norm_tf])
        idx = 0
        new_col = ["Normalized TF"]    
        df.insert(loc=idx, column='Document', value=new_col)
        print(df)
    return tf_doc

tf_doc = compute_normalizedtf([doc1, doc2, doc3])

        Document  something    I   in  life  learning   to  start  want  \
0  Normalized TF        0.1  0.1  0.1   0.1       0.1  0.2    0.1   0.1   

   charge  
0     0.1  
        Document  something   life   else    one  knows     no  about  reading
0  Normalized TF      0.125  0.125  0.125  0.125  0.125  0.125  0.125    0.125
        Document      stop  learning     Never
0  Normalized TF  0.333333  0.333333  0.333333


Inverse document Frequency

In [ ]:
tf_doc[2]

{'Never': 0.3333333333333333,
 'learning': 0.3333333333333333,
 'stop': 0.3333333333333333}

In [ ]:
import math

In [ ]:
def inverseDocumentFrequency(term, allDocuments):
    numDocumentsWithThisTerm = 0
    for doc in range (0, len(allDocuments)):
        if term.lower() in allDocuments[doc].lower().split():
            numDocumentsWithThisTerm = numDocumentsWithThisTerm + 1
 
    if numDocumentsWithThisTerm > 0:
        return 1.0 + math.log(float(len(allDocuments)) / numDocumentsWithThisTerm)
    else:
        return 1.0

In [ ]:
def compute_idf(documents):
    idf_dict = {}
    for doc in documents:
        sentence = doc.split()
        for word in sentence:
            idf_dict[word] = inverseDocumentFrequency(word, documents)
    return idf_dict
    
idf_dict = compute_idf([doc1, doc2, doc3])

compute_idf([doc1, doc2, doc3])

{'I': 2.09861228866811,
 'Never': 2.09861228866811,
 'about': 2.09861228866811,
 'charge': 2.09861228866811,
 'else': 2.09861228866811,
 'in': 2.09861228866811,
 'knows': 2.09861228866811,
 'learning': 1.4054651081081644,
 'life': 1.4054651081081644,
 'no': 2.09861228866811,
 'one': 2.09861228866811,
 'reading': 2.09861228866811,
 'something': 1.4054651081081644,
 'start': 2.09861228866811,
 'stop': 2.09861228866811,
 'to': 2.09861228866811,
 'want': 2.09861228866811}

TF * IDF

In [ ]:
# tf-idf score across all docs for the query string("life learning")
def compute_tfidf_with_alldocs(documents , query):
    tf_idf = []
    index = 0
    query_tokens = query.split()
    df = pd.DataFrame(columns=['doc'] + query_tokens)
    for doc in documents:
        df['doc'] = np.arange(0 , len(documents))
        doc_num = tf_doc[index]
        sentence = doc.split()
        for word in sentence:
            for text in query_tokens:
                if(text == word):
                    idx = sentence.index(word)
                    tf_idf_score = doc_num[word] * idf_dict[word]
                    tf_idf.append(tf_idf_score)
                    df.iloc[index, df.columns.get_loc(word)] = tf_idf_score
        index += 1
    df.fillna(0 , axis=1, inplace=True)
    return tf_idf , df
            
documents = [doc1, doc2, doc3]
tf_idf , df = compute_tfidf_with_alldocs(documents , query)
print(df)

   doc      life  learning
0    0  0.140547  0.140547
1    1  0.175683  0.000000
2    2  0.000000  0.468488


In [ ]:
# Train Document Set:
d1 = "The sky is blue."
d2 = "The sun is bright."

# Test Document Set:
d3 = "The sun in the sky is bright."
d4 = "We can see the shining sun, the bright sun."

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [ ]:
# set of documents
train = ['The sky is blue.','The sun is bright.']
test = ['The sun in the sky is bright', 'We can see the shining sun, the bright sun.']
# instantiate the vectorizer object
countvectorizer = CountVectorizer(analyzer= 'word', stop_words='english')
tfidfvectorizer = TfidfVectorizer(analyzer='word',stop_words= 'english')

In [ ]:
# convert the train documents into a matrix
count_wm = countvectorizer.fit_transform(train)
tfidf_wm = tfidfvectorizer.fit_transform(train)


In [ ]:
#count_tokens = tfidfvectorizer.get_feature_names() # no difference
count_tokens = countvectorizer.get_feature_names()
tfidf_tokens = tfidfvectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
count_tokens

['blue', 'bright', 'sky', 'sun']

In [ ]:
df_countvect = pd.DataFrame(data = count_wm.toarray(),index = ['Doc1','Doc2'],columns = count_tokens)
df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),index = ['Doc1','Doc2'],columns = tfidf_tokens)

In [ ]:
print("Count Vectorizer\n")
print(df_countvect)
print("\nTD-IDF Vectorizer\n")
print(df_tfidfvect)

Count Vectorizer

      blue  bright  sky  sun
Doc1     1       0    1    0
Doc2     0       1    0    1

TD-IDF Vectorizer

          blue    bright       sky       sun
Doc1  0.707107  0.000000  0.707107  0.000000
Doc2  0.000000  0.707107  0.000000  0.707107


In [ ]:
term_vectors  = countvectorizer.transform(test)
print("Sparse Matrix form of test data : \n")
print(term_vectors.todense())

Sparse Matrix form of test data : 

[[0 1 1 1]
 [0 1 0 2]]


In [ ]:
tfidf_term_vectors  = tfidfvectorizer.transform(test)
print("Sparse Matrix form of test data : \n")
tfidf_term_vectors.todense()

Sparse Matrix form of test data : 



matrix([[0.        , 0.57735027, 0.57735027, 0.57735027],
        [0.        , 0.4472136 , 0.        , 0.89442719]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
query = ["sun in the sky"]
query_vec = tfidfvectorizer.transform(query)

In [ ]:
results = cosine_similarity(tfidf_wm, query_vec)

In [ ]:
results

array([[0.5],
       [0.5]])

In [ ]:
res = np.argsort(results, axis=0)
print(res)

[[0]
 [1]]


2

In [ ]:
res[-2:][::-1]

array([[1],
       [0]])

In [ ]:
k=1
for i in res[-2:][::-1]:
    print("result ", k, "=============================")
    print(train[i[0]])
    print("=============================")
    k+=1

result  1 =============================
The sun is bright.
result  2 =============================
The sky is blue.


In [ ]:
documents = ['Machine learning is the study of computer algorithms that improve automatically through experience.\
Machine learning algorithms build a mathematical model based on sample data, known as training data.\
The discipline of machine learning employs various approaches to teach computers to accomplish tasks \
where no fully satisfactory algorithm is available.',
'Machine learning is closely related to computational statistics, which focuses on making predictions using computers.\
The study of mathematical optimization delivers methods, theory and application domains to the field of machine learning.',
'Machine learning involves computers discovering how they can perform tasks without being explicitly programmed to do so. \
It involves computers learning from data provided so that they carry out certain tasks.',
'Machine learning approaches are traditionally divided into three broad categories, depending on the nature of the "signal"\
or "feedback" available to the learning system: Supervised, Unsupervised and Reinforcement',
'Software engineering is the systematic application of engineering approaches to the development of software.\
Software engineering is a computing discipline.',
'A software engineer creates programs based on logic for the computer to execute. A software engineer has to be more concerned\
about the correctness of the program in all the cases. Meanwhile, a data scientist is comfortable with uncertainty and variability.\
Developing a machine learning application is more iterative and explorative process than software engineering.'
]

In [ ]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
import re
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer 
from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
documents_df=pd.DataFrame(documents,columns=['documents'])

In [ ]:
# removing special characters and stop words from the text
stop_words_l=stopwords.words('english')
documents_df['documents_cleaned']=documents_df.documents.apply(lambda x: " ".join(re.sub(r'[^a-zA-Z]',' ',w).lower() for w in x.split() if re.sub(r'[^a-zA-Z]',' ',w).lower() not in stop_words_l) )


In [ ]:
documents_df

documents  \
0  Machine learning is the study of computer algo...   
1  Machine learning is closely related to computa...   
2  Machine learning involves computers discoverin...   
3  Machine learning approaches are traditionally ...   
4  Software engineering is the systematic applica...   
5  A software engineer creates programs based on ...   

                                   documents_cleaned  
0  machine learning study computer algorithms imp...  
1  machine learning closely related computational...  
2  machine learning involves computers discoverin...  
3  machine learning approaches traditionally divi...  
4  software engineering systematic application en...  
5  software engineer creates programs based logic...

In [ ]:
countvectorizer = CountVectorizer(analyzer= 'word', stop_words='english')
tfidfvectorizer = TfidfVectorizer(analyzer='word',stop_words= 'english')

In [ ]:
count_wm = countvectorizer.fit_transform(documents_df.documents_cleaned)
tfidf_wm = tfidfvectorizer.fit_transform(documents_df.documents_cleaned)

In [ ]:
count_tokens = countvectorizer.get_feature_names()
tfidf_tokens = tfidfvectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
df_countvect = pd.DataFrame(data = count_wm.toarray(),index = ['Doc1','Doc2','Doc3','Doc4','Doc5','Doc6'],columns = count_tokens)
df_tfidfvect = pd.DataFrame(data = tfidf_wm.toarray(),index = ['Doc1','Doc2','Doc3','Doc4','Doc5','Doc6'],columns = tfidf_tokens)

In [ ]:
df_countvect

accomplish  algorithm  algorithms  application  approaches  \
Doc1           1          1           2            0           1   
Doc2           0          0           0            1           0   
Doc3           0          0           0            0           0   
Doc4           0          0           0            0           1   
Doc5           0          0           0            1           1   
Doc6           0          0           0            1           0   

      automatically  available  based  broad  build  ...  tasks  teach  \
Doc1              1          1      1      0      1  ...      1      1   
Doc2              0          0      0      0      0  ...      0      0   
Doc3              0          0      0      0      0  ...      2      0   
Doc4              0          1      0      1      0  ...      0      0   
Doc5              0          0      0      0      0  ...      0      0   
Doc6              0          0      1      0      0  ...      0      0   

      theory  traditionally  training  uncertainty  unsupervised  using  \
Doc1       0              0         1            0             0      0   
Doc2       1              0         0            0             0      1   
Doc3       0              0         0            0             0      0   
Doc4       0              1         0            0             1      0   
Doc5       0              0         0            0             0      0   
Doc6       0              0         0            1             0      0   

      variability  various  
Doc1            0        1  
Doc2            0        0  
Doc3            0        0  
Doc4            0        0  
Doc5            0        0  
Doc6            1        0  

[6 rows x 84 columns]

In [ ]:
df_tfidfvect

accomplish  algorithm  algorithms  application  approaches  \
Doc1    0.178721   0.178721    0.357443     0.000000    0.123731   
Doc2    0.000000   0.000000    0.000000     0.161382    0.000000   
Doc3    0.000000   0.000000    0.000000     0.000000    0.000000   
Doc4    0.000000   0.000000    0.000000     0.000000    0.188675   
Doc5    0.000000   0.000000    0.000000     0.169236    0.169236   
Doc6    0.000000   0.000000    0.000000     0.127351    0.000000   

      automatically  available     based     broad     build  ...     tasks  \
Doc1       0.178721   0.146554  0.146554  0.000000  0.178721  ...  0.146554   
Doc2       0.000000   0.000000  0.000000  0.000000  0.000000  ...  0.000000   
Doc3       0.000000   0.000000  0.000000  0.000000  0.000000  ...  0.393183   
Doc4       0.000000   0.223477  0.000000  0.272528  0.000000  ...  0.000000   
Doc5       0.000000   0.000000  0.000000  0.000000  0.000000  ...  0.000000   
Doc6       0.000000   0.000000  0.150842  0.000000  0.000000  ...  0.000000   

         teach    theory  traditionally  training  uncertainty  unsupervised  \
Doc1  0.178721  0.000000       0.000000  0.178721     0.000000      0.000000   
Doc2  0.000000  0.233105       0.000000  0.000000     0.000000      0.000000   
Doc3  0.000000  0.000000       0.000000  0.000000     0.000000      0.000000   
Doc4  0.000000  0.000000       0.272528  0.000000     0.000000      0.272528   
Doc5  0.000000  0.000000       0.000000  0.000000     0.000000      0.000000   
Doc6  0.000000  0.000000       0.000000  0.000000     0.183951      0.000000   

         using  variability   various  
Doc1  0.000000     0.000000  0.178721  
Doc2  0.233105     0.000000  0.000000  
Doc3  0.000000     0.000000  0.000000  
Doc4  0.000000     0.000000  0.000000  
Doc5  0.000000     0.000000  0.000000  
Doc6  0.000000     0.183951  0.000000  

[6 rows x 84 columns]

In [ ]:
query = ["software engineering"]
query_vec = tfidfvectorizer.transform(query)
query_vec.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.70710678,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.70710678,
         0.        , 0.        , 0

In [ ]:
results = cosine_similarity(tfidf_wm, query_vec)

In [ ]:
res = np.argsort(results, axis=0)

In [ ]:
k=1
for i in res[-1:-3:-1]:
    print("result ", k, "=============================")
    print(documents[i[0]])
    print("=============================")
    k+=1

result  1 =============================
Software engineering is the systematic application of engineering approaches to the development of software.Software engineering is a computing discipline.
result  2 =============================
A software engineer creates programs based on logic for the computer to execute. A software engineer has to be more concernedabout the correctness of the program in all the cases. Meanwhile, a data scientist is comfortable with uncertainty and variability.Developing a machine learning application is more iterative and explorative process than software engineering.
